"""One self-contained HTML file with the result of a run.

Images are inlined as base64 so the report can be mailed, dropped into a CI
artifact or opened from a flash drive years later and still show its pictures.
"""

import base64
import datetime
import html
import os

CSS = """
:root { color-scheme: light dark; }
* { box-sizing: border-box; }
body { margin: 0; padding: 32px; background: #f6f6f8; color: #16161a;
       font: 15px/1.5 -apple-system, "SF Pro Text", Helvetica, Arial, sans-serif; }
h1 { margin: 0 0 4px; font-size: 24px; letter-spacing: -0.4px; }
.sub { color: #6b6b76; margin: 0 0 24px; font-size: 13px; }
.tiles { display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 28px; }
.tile { background: #fff; border: 1px solid #e2e2e8; border-radius: 12px;
        padding: 12px 18px; min-width: 110px; }
.tile b { display: block; font-size: 26px; line-height: 1.2; }
.tile span { font-size: 12px; color: #6b6b76; text-transform: uppercase;
             letter-spacing: 0.6px; }
.case { background: #fff; border: 1px solid #e2e2e8; border-radius: 12px;
        margin-bottom: 16px; overflow: hidden; }
.case > header { display: flex; align-items: center; gap: 12px;
                 padding: 14px 18px; border-bottom: 1px solid #eeeef2; }
.case h2 { margin: 0; font-size: 16px; font-weight: 600; }
.case .note { margin-left: auto; color: #6b6b76; font-size: 13px; }
.badge { font-size: 11px; font-weight: 700; text-transform: uppercase;
         letter-spacing: 0.7px; padding: 4px 9px; border-radius: 999px; }
.pass { background: #e3f7e8; color: #1c7a34; }
.fail { background: #fde5e9; color: #b0142f; }
.new { background: #e6effd; color: #1f5ecb; }
.missing { background: #fdf0e0; color: #99600c; }
.shots { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px;
         padding: 18px; }
.shots figure { margin: 0; }
.shots figcaption { font-size: 12px; color: #6b6b76; margin-bottom: 6px;
                    text-transform: uppercase; letter-spacing: 0.6px; }
.shots img { width: 100%; border: 1px solid #e2e2e8; border-radius: 8px;
             background: #fff; display: block; }
.empty { border: 1px dashed #d6d6de; border-radius: 8px; padding: 24px;
         text-align: center; color: #9a9aa4; font-size: 13px; }
footer { color: #9a9aa4; font-size: 12px; margin-top: 28px; }
@media (max-width: 760px) { .shots { grid-template-columns: 1fr; } }
"""


def _inline(path):
    if not path or not os.path.exists(path):
        return None
    with open(path, "rb") as fh:
        return "data:image/png;base64," + base64.b64encode(fh.read()).decode("ascii")


def _figure(caption, path, empty_text):
    src = _inline(path)
    body = (
        '<img src="%s" alt="%s">' % (src, html.escape(caption))
        if src
        else '<div class="empty">%s</div>' % html.escape(empty_text)
    )
    return '<figure><figcaption>%s</figcaption>%s</figure>' % (
        html.escape(caption),
        body,
    )


def render(results, title="Screenshot regression", device=""):
    """Return the report as an HTML string."""
    counts = {"pass": 0, "fail": 0, "new": 0, "missing": 0}
    for r in results:
        counts[r.status] = counts.get(r.status, 0) + 1

    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    subtitle = "%s · %d cases" % (stamp, len(results))
    if device:
        subtitle = "%s · %s" % (device, subtitle)

    tiles = "".join(
        '<div class="tile"><b>%d</b><span>%s</span></div>' % (counts[k], k)
        for k in ("pass", "fail", "new", "missing")
    )

    cases = []
    for r in results:
        note = r.message
        if r.status in ("pass", "fail") and r.total_pixels:
            note = "%s · %.3f%% changed, threshold %.3f%%" % (
                r.message,
                r.percent,
                r.threshold * 100.0,
            )
        cases.append(
            '<section class="case"><header><h2>%s</h2>'
            '<span class="badge %s">%s</span>'
            '<span class="note">%s</span></header><div class="shots">%s%s%s</div>'
            "</section>"
            % (
                html.escape(r.name),
                r.status,
                r.status,
                html.escape(note),
                _figure("baseline", r.baseline_path, "no baseline"),
                _figure("current", r.current_path, "not captured"),
                _figure("diff", r.diff_path, "no difference"),
            )
        )

    return (
        "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">"
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        "<title>%s</title><style>%s</style></head><body>"
        "<h1>%s</h1><p class=\"sub\">%s</p><div class=\"tiles\">%s</div>%s"
        "<footer>Generated by xcshot. Images are embedded, the file stands alone."
        "</footer></body></html>"
        % (
            html.escape(title),
            CSS,
            html.escape(title),
            html.escape(subtitle),
            tiles,
            "".join(cases),
        )
    )


def write(path, results, title="Screenshot regression", device=""):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(render(results, title=title, device=device))
    return path
